version: '3.8'

services:
  backend:
    container_name: backend
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: unless-stopped
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456789@abc"
    ports:
      - 8000:8000