version: '3.8'
services:
  backend:
    container_name: backend
    image: mcr.microsoft.com/mssql/server:2017-latest
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "123456789@abc"
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: mcr.microsoft.com/mssql/server:2017-latest
    restart: always
    environment:
      MSSQL_DATABASE: auth
      MSSQL_USER: root
      MSSQL_PASSWORD: root
      MSSQL_ROOT_PASSWORD: root